version: "3"
services:
  app:
    build:
      context: .
    volumes:
      - .:/base_project
  postgres:
    image: postgres
    ports:
      - "15432:5432"
    volumes:
      - ./docker/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - 8000:80
    volumes:
      - ./docker/pgadmin4:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - postgres
