version: "3"
services:
  app:
    build:
      context: .
    volumes:
      - .:/base_project
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
